### ISSUE TITLE
Upload Visual Studio Code extension to Open VSX

### ISSUE THREAD

**Issue by saerosV** [curlconverter/curlconverter-vscode#2]
#### Describe the issue

As stated in the [Archlinux Wiki](https://wiki.archlinux.org/title/Visual_Studio_Code#Extensions_support), the open-source builds of VSCode (Code, VSCodium) don't have access to [Microsoft's Marketplace](https://marketplace.visualstudio.com/vscode). Instead, they use the [Open VSX](https://open-vsx.org/) registry.

To increase curlconverter's extension visibility, and facilitate users' experience, I suggest uploading the VSCode extension to the [Open VSX](https://open-vsx.org/) registry.

#### Useful links

- [Publishing extensions in OpenVSX](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions).

**Comment by verhovsky** [comment]
Done: https://open-vsx.org/extension/curlconverter/curlconverter

Let me know if you run into issues.
