### ISSUE TITLE
Feature Request - Add command for unsaved files

### ISSUE THREAD

**Issue by dylancaponi** [curlconverter/curlconverter-vscode#3]
I find myself using this extension on temporary, unsaved files without an associated filetype.

For these undefined files, it would be awesome to have the menu sub-option to select which language:
"Past cURL as code > Python, JavaScript, PHP, R, etc..."

**Comment by dylancaponi** [comment]
Thank you!

**Comment by verhovsky** [comment]
Thank you for the suggestion and thank you for the thank you
